import { motion } from "framer-motion";
import { NavLink } from "react-router-dom";
import { Brain, Target, BarChart3, Rocket, ArrowRight } from "lucide-react";
import SpotlightCard from "../components/SpotlightCard";
import ShinyText from "../components/ShinyText";
import GradientText from "../components/GradientText";

const features = [
    {
        icon: Brain,
        title: "AI Analysis",
        desc: "Get AI-powered insights on your skill gaps and stagnation risks",
        color: "from-violet-500 to-purple-600",
    },
    {
        icon: Target,
        title: "Smart Roadmaps",
        desc: "Personalized week-by-week learning plans generated by AI",
        color: "from-cyan-500 to-blue-600",
    },
    {
        icon: BarChart3,
        title: "Progress Tracking",
        desc: "Visualize your growth with charts and track skill improvements over time",
        color: "from-emerald-500 to-green-600",
    },
    {
        icon: Rocket,
        title: "Career Ready",
        desc: "Bridge the gap between where you are and where you want to be",
        color: "from-orange-500 to-red-500",
    },
];

export default function Landing() {
    return (
        <div className="min-h-screen text-white overflow-hidden">
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <div className="absolute -top-40 -left-40 w-[500px] h-[500px] bg-purple-600/20 rounded-full blur-[128px] animate-blob" />
                <div className="absolute top-60 -right-40 w-[400px] h-[400px] bg-cyan-600/15 rounded-full blur-[128px] animate-blob animation-delay-2000" />
                <div className="absolute -bottom-40 left-1/3 w-[450px] h-[450px] bg-emerald-600/10 rounded-full blur-[128px] animate-blob animation-delay-4000" />
            </div>

            <section className="relative max-w-6xl mx-auto px-6 pt-24 pb-20">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.7 }}
                    className="text-center"
                >
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gray-900/60 border border-gray-800 text-sm text-gray-300 mb-8">
                        <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
                        <ShinyText text="Powered by AI Intelligence" speed={3} color="#9ca3af" shineColor="#e0e7ff" />
                    </div>

                    <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight leading-tight">
                        <GradientText colors={["#818cf8", "#a78bfa", "#ec4899"]} animationSpeed={5} className="inline">
                            Master Any Skill
                        </GradientText>
                        <br />
                        <span className="text-white">with AI Intelligence</span>
                    </h1>

                    <p className="mt-6 text-lg md:text-xl text-gray-400 max-w-2xl mx-auto leading-relaxed">
                        Cortexa analyzes your skills, identifies growth opportunities, and builds
                        personalized learning roadmaps — so you grow faster and smarter.
                    </p>

                    <div className="mt-10 flex flex-wrap justify-center gap-4">
                        <NavLink
                            to="/register"
                            className="group inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-white text-black font-semibold text-lg hover:shadow-[0_0_40px_rgba(255,255,255,0.2)] transition-all duration-300"
                        >
                            Get Started Free
                            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                        </NavLink>

                        <NavLink
                            to="/login"
                            className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl border border-gray-700 text-white font-semibold text-lg hover:border-gray-500 hover:bg-gray-900/50 transition-all duration-300"
                        >
                            Sign In
                        </NavLink>
                    </div>
                </motion.div>
            </section>

            <section className="relative max-w-6xl mx-auto px-6 pb-24">
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.7, delay: 0.3 }}
                >
                    <div className="text-center mb-14">
                        <h2 className="text-3xl md:text-4xl font-bold">
                            Everything you need to <span className="text-purple-400">accelerate growth</span>
                        </h2>
                        <p className="text-gray-400 mt-3 max-w-xl mx-auto">
                            Stop guessing. Let AI analyze your skill profile and build a roadmap that actually works.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                        {features.map((f, idx) => (
                            <motion.div
                                key={f.title}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5, delay: 0.4 + idx * 0.1 }}
                            >
                                <SpotlightCard
                                    className="group glass p-7 hover:-translate-y-1 transition-all duration-300 h-full"
                                    spotlightColor="rgba(139, 92, 246, 0.2)"
                                >
                                    <div className={`inline-flex p-3 rounded-2xl bg-gradient-to-br ${f.color}`}>
                                        <f.icon className="w-6 h-6 text-white" />
                                    </div>
                                    <h3 className="text-xl font-semibold mt-4">{f.title}</h3>
                                    <p className="text-gray-400 mt-2 leading-relaxed">{f.desc}</p>
                                </SpotlightCard>
                            </motion.div>
                        ))}
                    </div>
                </motion.div>
            </section>

            <section className="relative max-w-6xl mx-auto px-6 pb-24">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.7, delay: 0.6 }}
                    className="text-center"
                >
                    <SpotlightCard className="glass p-10 md:p-14" spotlightColor="rgba(168, 85, 247, 0.2)">
                        <h2 className="text-3xl md:text-4xl font-bold">Ready to level up?</h2>
                        <p className="text-gray-400 mt-3 max-w-lg mx-auto">
                            Join Cortexa and let AI intelligence drive your career growth
                        </p>
                        <NavLink
                            to="/register"
                            className="inline-flex items-center gap-2 mt-8 px-8 py-4 rounded-2xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-semibold text-lg hover:shadow-[0_0_40px_rgba(139,92,246,0.3)] transition-all duration-300"
                        >
                            Start Your Journey
                            <ArrowRight className="w-5 h-5" />
                        </NavLink>
                    </SpotlightCard>
                </motion.div>
            </section>

            <footer className="relative border-t border-gray-800/50 mt-10">
                <div className="max-w-6xl mx-auto px-6 py-10 flex flex-col md:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-md bg-gradient-to-br from-purple-500 to-pink-500 grid place-items-center text-white text-[10px] font-bold">C</div>
                        <span className="text-sm text-gray-400">© 2026 Cortexa. All rights reserved.</span>
                    </div>
                    <div className="flex items-center gap-6 text-sm text-gray-500">
                        <NavLink to="/login" className="hover:text-gray-300 transition">Sign In</NavLink>
                        <NavLink to="/register" className="hover:text-gray-300 transition">Register</NavLink>
                    </div>
                </div>
            </footer>
        </div>
    );
}
